### ISSUE TITLE
incorrect event latitude output

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/PhasePApy#10]
The event latitude is coming as zero in the test/1d example. 

See this line: https://github.com/GeoscienceAustralia/PhasePApy/blob/master/tests/test_1dassociator.py#L89

Investigate and fix please.

**Comment by sudhirJain** [comment]
Hi Sudipta,

I have fixed the issue for incorrect latitude.

Shortly I will move assoc1D and plot1D file in the repository.

Regards,

Sudhir Jain

**Comment by sudhirJain** [comment]
Issue Fixed
